import os
import discord
from discord.ext import commands
#from discord_slash import SlashCommand
import google.doc_creator as doc_creator
import webscraper.webScraper as scraper

TOKEN = open("/home/pi/Python/A-Little-Help/Token.txt", "r").readline()
BOT_LINK = open("/home/pi/Python/A-Little-Help/botAccessLink.txt", "r").readline()
GUILD = 'Davidamiright?'
CODE_KEY = 250
SECRET_ERROR = "Spaghetti"

#intents=discord.Intents.all()
intents = discord.Intents.default()
intents.message_content = True
intents.members = True
bot = commands.Bot(command_prefix = '!', intents = intents)
#slash = SlashCommand(bot, sync_commands=True)


google = doc_creator.Doc_Creator()


####################################################################################################################################################################

@bot.event
async def on_ready():
    for guild in bot.guilds:
        if guild.name == GUILD:
            break    
    print(f'{bot.user} is connected to the following guild')
    print(f'Guild Name: {guild.name}')
    print(f'Guild ID: {guild.id}')
    

###########################################################################################################################################################################################

@bot.event
async def on_message(message):
    if message.author == bot.user:
        return
    if "a little help" in message.content.lower():
        #await message.channel.send("Did you need my help?\nType !help to see how I can assist you")
        gif_file = discord.File("/home/pi/Python/A-Little-Help/ALittleHelp.gif", filename="ALittleHelp.gif")
        embed = discord.Embed(title="Did you need my help?", description="\nType !help to see what I can do!", colour = discord.Colour.green())
        embed.set_image(url="attachment://ALittleHelp.gif")
        await message.channel.send(file=gif_file, embed=embed)

    if str(message.author) == "Chicken-Chan#7185":
        await message.add_reaction("\N{Chicken}")
    
    userFilePath = "/home/pi/Python/A-Little-Help/Users/" + str(message.author.id) + ".txt"
    if not os.path.exists(userFilePath):
        file = open(userFilePath, "w")
        file.write("0")
        file.close()
    file = open(userFilePath, "r")
    numPosts = int(file.readline())
    file.close()
    numPosts += 1
    file = open(userFilePath, "w")
    file.write(str(numPosts))
    file.close()
    
    await bot.process_commands(message)


######################################################################################################################################################################################


@bot.command()
#@slash.slash(name="ping", description="Gets bots ping")
async def ping(ctx):
    await ctx.send(f' Pong! {round(bot.latency * 1000)}ms')
    

######################################################################################################################################################################################


@bot.command()
#@slash.slash(name="info", description="Get IDs")
#@commands.is_owner()
async def info(ctx):
    await ctx.send(f'Bot Info = {bot.user} \nUser ID = {ctx.author}\nGuild Name = {ctx.guild} \nGuild ID = {ctx.guild.id}\nUse !help for help with commands')
    

###############################################################################################################################################################################



#delete default help command
bot.remove_command('help')

@bot.command(pass_context=True)
#@slash.slash(name="help", description="Shows all of bots functions")
async def help(ctx):
    embed = discord.Embed(colour = discord.Colour.green())
    embed.set_author(name='List of Commands')
    embed.add_field(name='!ping', value='Returns bot respond time in milliseconds', inline=False)
    embed.add_field(name='!info', value='Gives bot id, user id, guild name, and guild id', inline=False)
    embed.add_field(name='!add', value='Adds numbers, ex: !add 3 4', inline=False)
    embed.add_field(name='!sub', value='Subtracts numbers, ex: !sub 10 5', inline=False)
    embed.add_field(name='!mult', value='Multiplies numbers ex: !mult 4 5', inline=False)
    embed.add_field(name='!div', value='Divides numbers ex: !div 6 2', inline=False)
    embed.add_field(name='!encode', value='Converts text into nonsense that can be decoded using decode command ex: !encode hello', inline=False)
    embed.add_field(name='!decode', value='Converts nonsense generated by !encode back into the original message ex: !decode űŬũŨš', inline=False)
    embed.add_field(name='!createDoc', value='Creates a Google Doc and returns a link to the doc', inline=False)
    embed.add_field(name='!createSlide', value='Creates a Google Slide and returns a link to the slide', inline=False)
    embed.add_field(name='!createSheet', value='Creates a Google Sheet and returns a link to the sheet', inline=False)
    embed.add_field(name='!addBot', value='Displays a link to add the bot to another server', inline=False)
    await ctx.send(embed=embed)


################################################################################################################################################################



@bot.command()
#@slash.slash(name="add", description="Add numbers")
async def add(ctx, arg1=None, *argv):
    flag = False
    try:
        sum = float(arg1)
    except:
        flag = True
        
    for arg in argv:
        if (flag):
            break
        try:
            sum = sum + float(arg)
        except ValueError:
            flag = True

    if (flag):
        await ctx.send(f'Invalid Input: Enter numbers seperated by spaces')
    else:        
        await ctx.send(f'= {sum}')


####################################################################################################################################



@bot.command()
#@slash.slash(name="mult", description="Multiply numbers")
async def mult(ctx, arg1=None, *argv):
    flag = False
    try:
        product = float(arg1)
    except:
        flag = True
    for arg in argv:
        if (flag):
            break
        try:
            product = product * float(arg)
        except ValueError:
            flag = True

    if (flag):
        await ctx.send(f'Invalid Input: Enter numbers seperated by spaces')
    else:        
        await ctx.send(f'= {product}')
        

#################################################################################################################################


@bot.command()
#@slash.slash(name="sub", description="Subtract numbers")
async def sub(ctx, arg1=None, *argv):
    flag = False
    try:
        difference = float(arg1)
    except:
        flag = True

         
    for arg in argv:
        if (flag):
            break
        try:
            difference = difference - float(arg)
        except ValueError:
            flag = True
            
    if (flag):
        await ctx.send(f'Invalid Input: Enter numbers seperated by spaces')
    else:        
        await ctx.send(f'= {difference}')
        

#######################################################################################################################


@bot.command()
#@slash.slash(name="div", description="Divide numbers")
async def div(ctx, arg1=None, *argv):
    flag = False

    try:
        quotient = float(arg1)
    except:
        flag = True
        
    for arg in argv:
        if (flag):
            break
        try:
            quotient = quotient / float(arg)
        except ValueError:
            flag = True
        except ZeroDivisionError:
            quotient = "Division by zero error"
            break

    if (flag):
        await ctx.send(f'Invalid Input: Enter numbers seperated by spaces')
    else:        
        await ctx.send(f'= {quotient}')        


#############################################################################################################################


@bot.command()
#@slash.slash(name="encode", description="Scambles text")
async def encode(ctx, *args):
    message = ""
    if (args):
        args = " ".join(args)
        for element in args:
            element = chr(ord(element) + CODE_KEY)
            message += element
        await ctx.send(message)
    else:
        for element in SECRET_ERROR:
            element = chr(ord(element) + CODE_KEY)
            message += element
        await ctx.send(message)


###############################################################################################################################



@bot.command()
#@slash.slash(name="decode", description="Descrambles text")
async def decode(ctx, *args):
    message = ""
    if (args):
        args = " ".join(args)
        for element in args:
            element = chr(ord(element) - CODE_KEY)
            message += element
        await ctx.send(message)
    else:
        await ctx.send("Invalid Input: You must provide text to decode")



###########################################################################################################################################


@bot.command()
#@slash.slash(name="createDoc", description="Creates a Google Doc file")
async def createDoc(ctx, *args):
    if (args):
        args = " ".join(args)
        url = google.createDoc(args)
        await ctx.send(url)
    else:
        url = google.createDoc()
        await ctx.send(url)


########################################################################################################################################################



@bot.command()
#@slash.slash(name="createSlide", description="Creates a Google Slide file")
async def createSlide(ctx, *args):
    if (args):
        args = " ".join(args)
        url = google.createSlide(args)
        await ctx.send(url)
    else:
        url = google.createSlide()
        await ctx.send(url)
    

###################################################################################################################################################################



@bot.command()
#@slash.slash(name="createSheet", description="Creates a Google Sheet file")
async def createSheet(ctx, *args):
    if (args):
        args = " ".join(args)
        url = google.createSheet(arg)
        await ctx.send(url)
    else:
        url = google.createSheet()
        await ctx.send(url)


##################################################################################################################################################################################

@bot.command()
async def youtube(ctx, *args):
    if (args):
        args = " ".join(args)
        url = scraper.getYoutubeVideo(args)
        if url:
            await ctx.send(url)
        else:
            await ctx.send("Oops I could'nt find a video for you...")
    else:
        url = scraper.getYoutubeVideo("muntjac")
        if url:
            await ctx.send(url)
        else:
            await ctx.send("Oops I could'nt find a video for you...")
##########################################################################################################################################################################



@bot.command()
#@slash.slash(name="addBot", description="Creates link to this add bot to a server")
async def addBot(ctx):
    await ctx.send(BOT_LINK)
    

################################################################################################################################################################################





bot.run(TOKEN)
