import discord
from discord.ext import commands

#The help cog is to provide help with all the bot commands, listing them all and providing examples for each of them
class Help(commands.Cog):

    def __init__(self, bot):
        self.bot = bot

    
    @commands.command(pass_context=True)
    async def help(self, ctx):
        embed = discord.Embed(colour = discord.Colour.green())
        embed.set_author(name='List of Commands')
        embed.add_field(name='!ping', value='Returns bot respond time in milliseconds', inline=False)
        embed.add_field(name='!info', value='Gives bot id, user id, guild name, and guild id', inline=False)
        embed.add_field(name='!add', value='Adds numbers, ex: !add 3 4', inline=False)
        embed.add_field(name='!sub', value='Subtracts numbers, ex: !sub 10 5', inline=False)
        embed.add_field(name='!mult', value='Multiplies numbers ex: !mult 4 5', inline=False)
        embed.add_field(name='!div', value='Divides numbers ex: !div 6 2', inline=False)
        embed.add_field(name='!encode', value='Converts text into nonsense that can be decoded using decode command ex: !encode hello', inline=False)
        embed.add_field(name='!decode', value='Converts nonsense generated by !encode back into the original message ex: !decode űŬũŨš', inline=False)
        embed.add_field(name='!createDoc', value='Creates a Google Doc and returns a link to the doc', inline=False)
        embed.add_field(name='!createSlide', value='Creates a Google Slide and returns a link to the slide', inline=False)
        embed.add_field(name='!createSheet', value='Creates a Google Sheet and returns a link to the sheet', inline=False)
        embed.add_field(name='!addBot', value='Displays a link to add the bot to another server', inline=False)
        embed.add_field(name='!youtube', value='Posts a link about a youtube video of your search query', inline=False)
        await ctx.send(embed=embed)

async def setup(bot):
    await bot.add_cog(Help(bot))